version: '2'

services:
  mongo:
    image: mongo:3.4-jessie
    ports:
      - 27017:27017
    expose:
      - 27017
    container_name: mongo
    network_mode: host
  eureka:
    build: eureka/
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8761:8761

  config-server:
    build: config-server/
    restart: always
    network_mode: "host"
    image: demo-config-service
    hostname: localhost
    ports:
      - 8888:8888

  zuulgateway:
    build: zuulgateway/
    depends_on:
      - config-server
      - eureka
      - musicx
      - userservice
    restart: always
    network_mode: "host"

    hostname: localhost
    ports:
      - 8050:8050

  musicx:
    build: musicx/
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8085:8085
    depends_on:
      - config-server
      - eureka

  userservice:
    build: userservice/
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8060:8060
    depends_on:
      - config-server
      - eureka

